server:
  port: ${PORT:8080}

services:
  users-url: ${USERS_URL:http://localhost:8083}
  catalog-url: ${CATALOG_URL:http://localhost:8081}
  orders-url: ${ORDERS_URL:http://localhost:8082}

public:
  base-url: ${BFF_PUBLIC_BASE:http://localhost:8080}

jwt:
  secret: ${JWT_SECRET}